### ISSUE TITLE
Reaching WebUI in local network

### ISSUE THREAD

**Issue by SHU-red** [oblique/dockerfiles#9]
Hi there,
ive got just a tiny question.
Thanks to your documentation, the following docker-compose-file is running for me:

```
services:
  mullvad_cli:
    image: oblique/mullvad:latest
    container_name: mullvad_cli
    cap_add:
      - NET_ADMIN               
      - SYS_MODULE   
    privileged: true
    environment:
      - TZ=Europe/London
    volumes:
      - /local/mullvad_cli_config:/config
    restart: unless-stopped

  firefox_vpn:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox_vpn
    depends_on:
      - mullvad_cli
    network_mode: service:mullvad_cli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /local/firefox_config:/config
    #ports:
    #  - 3002:3000
    shm_size: "1gb"
    restart: unless-stopped

```

But using `network_mode: service:x` is inhibiting the use of ports
Can you tell me what i have to do if i still want to reach the firefox_vpn services web-ui in my local network?

Thanks
